language: python
python:  
   - "3.6"
install:  
  - pip install -e . 
  - pip install pytest-cov codecov   
# Install packages for code coverage report
script:  
  - pytest --cov=test
after_success:
  - codecov
public_gcs:
  service: GCS
  bucket: "storage_bucket01"
  credentials: 'gs://cloud-training-demos/taxifare/large/taxi-train*.csv'
  public: true